Repository teamBeNU/SSOP_Expo, pull requests merged in 2024-12, with the labels that each got.

#116 [FEAT} #114 sample card
  app.json
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  package-lock.json
  package.json
Labels: ➕ feat, 🌕 frontend

#120 [FIX} 내 카드 갤러리에 저장 및 온보딩 스크롤
  components/Avatar/AvatarCustom.js
  components/MyCard/Card.js
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardFront.js
  package-lock.json
  package.json
  pages/Onboarding/Onboarding.js
  pages/Onboarding/OnboardingStyle.js
  utils/avatarCapture.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#121 [FIX]#118 카드 삭제 모달
  components/MyCard/CardDetailView.js
  components/MyCard/CardViewStyle.js
  components/MyCard/DeleteCardAPI.js
  components/MyCard/ListCardView.js
  pages/MyCard/DeleteMyCard.js
  pages/MyCard/MyCardStyle.js
Labels: ➕ feat, 🌕 frontend

#123 [FEAT] 팀스페이스 카드 상세보기 페이지
  App.js
  components/Space/Memo.js
  components/Space/MySpaceDetailView.js
  components/Space/TeamspCardDetailView.js
Labels: ➕ feat, 🌕 frontend

#124 [FIX] 그룹 상세 보기
  App.js
  assets/icons/ic_RightArrow_small_line.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/NoCardsView.js
  components/Bluetooth/ShareCardStyle.js
  components/MyCard/MemoStyle.js
  components/Space/AcceptCardView.js
  components/Space/ExchangeModal.js
  components/Space/ExchangeModalStyle.js
  components/Space/SpaceModal.js
  pages/Bluetooth/BluetoothStyle.js
  pages/CheckCard/CheckCardDetail.js
  pages/LinkShare/LinkShareStyle.js
  pages/Notify/Notify.js
  pages/Notify/NotifyStyle.js
  pages/Space/DetailGroup.js
  pages/Space/MySpace.js
  pages/Space/Space.js
  pages/Space/SpaceStyle.js
Labels: 🌕 frontend, 📌 fix

#126 [FIX} 카드 생성 관련 수정
  assets/teamSp/graphic_invite.svg
  components/CreateCard/SelectCover.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateStyles.js
  components/CreateCard/TemplateWorker.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/EnterTeamSp/HostFanFalse.js
  components/EnterTeamSp/HostFanTrue.js
  components/EnterTeamSp/HostStudentFalse.js
  components/EnterTeamSp/HostStudentTrue.js
  components/EnterTeamSp/HostTemplate.js
  components/EnterTeamSp/HostWorkerFalse.js
  components/EnterTeamSp/HostWorkerTrue.js
  pages/CreateCard/CreateCard.js
  pages/CreateCard/CreateCardStyle.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/CreateTeamSp/CreateTmSpStyle.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
Labels: 🌕 frontend, 📌 fix

#128 [FIX] #127 QA 적용
  App.js
  assets/favicon.png
  assets/icon.png
  assets/icons/ic_RightArrow_small_line.svg
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardFront.js
  components/MyCard/CardStyle.js
  components/MyCard/CardViewStyle.js
  components/MyCard/DeleteCardAPI.js
  components/MyCard/GridCardView.js
  pages/Login/Login.js
  pages/Login/LoginStyle.js
  pages/Login/SignUp.js
  pages/Login/SignUpStyle.js
  pages/MyCard/EditCard.js
  pages/MyCard/EditCardStyle.js
  pages/MyCard/MyCard.js
  pages/MyCard/MyCardStyle.js
  pages/MyCard/MyCardsView.js
  pages/MyCard/MyCardsViewStyle.js
  textStyles.js
Labels: 🌕 frontend, 📌 fix

#129 [Fix]#117 QA 수정
  App.js
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/ShareCardStyle.js
  components/Space/ExchangeModal.js
  components/Space/ExchangeModalStyle.js
  pages/LinkShare/LinkShare.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
  pages/Space/DetailTeamSpace.js
  pages/Space/EditGroupPage.js
  pages/Space/EditTeamSpace.js
  pages/Space/SpaceStyle.js
  pages/home/HomeStyle.js
Labels: 🌕 frontend, 📌 fix

#130 [FIX} QA 적용
  App.js
  assets/icons/ic_toggle_off.svg
  assets/icons/ic_toggle_on.svg
  components/CreateCard/TemplateStudentSchool.js
  components/MyCard/CardStyle.js
  components/MyCard/Memo.js
  components/MyCard/MemoStyle.js
  pages/Login/SignUp.js
  pages/MyCard/MyCard.js
Labels: 🌕 frontend, 📌 fix

#131 [FIX} #119 QA 적용
  components/CreateCard/FreeTemplate/SelectTextInput.js
  components/CreateCard/SelectCover.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateStyles.js
  components/CreateCard/TemplateWorker.js
  components/EnterTeamSp/HostFanFalse.js
  components/EnterTeamSp/HostFanTrue.js
  pages/CreateCard/CreateCard.js
  pages/CreateCard/CreateCardStyle.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/CreateTeamSp/CreateTmSpStyle.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/MyCard/EditCard.js
  pages/MyPage/MyPage.js
  pages/MyPage/MyPageStyle.js
  pages/MyPage/UserAccount.js
  pages/MyPage/UserInfoStyle.js
  pages/MyPage/UserPw.js
Labels: 🌕 frontend, 📌 fix

#132 [FIX] QA - QR, 검색, 팀스페이스
  components/Bluetooth/BottomSheetStyle.js
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ListCardsViewStyle.js
  components/Bluetooth/QRBottomSheet.js
  components/Bluetooth/ShareCardStyle.js
  components/Bluetooth/TeamspCardsView.js
  components/EnterTeamSp/HostTemplate.js
  components/MyCard/MemoStyle.js
  components/Space/ExchangeModalStyle.js
  components/Space/Memo.js
  components/Space/SpaceModalStyle.js
  components/Space/TeamspCardDetailView.js
  package-lock.json
  pages/Bluetooth/Bluetooth.js
  pages/Bluetooth/BluetoothStyle.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/SearchCard/HomeSearchCard.js
  pages/SearchCard/SearchCardStyle.js
  pages/SearchCard/SearchMySpace.js
  pages/SearchCard/SearchTeamSp.js
  pages/Space/DetailTeamSpace.js
  pages/Space/DetailTeamSpaceScreen.js
  pages/Space/SpaceStyle.js
  pages/Space/TeamSpace.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#135 [FIX[ #133 2차 QA
  App.js
  assets/fonts/pretendard-bold.otf
  components/CreateCard/TemplateStudentSchool.js
  pages/Onboarding/Onboarding.js
  pages/Onboarding/OnboardingStyle.js
Labels: 🌕 frontend, 📌 fix

#136 [FIX] 2차 QA
  components/Bluetooth/ShareCard.js
  components/Bluetooth/ShareCardStyle.js
  pages/MyCard/MyCard.js
  pages/Space/Space.js
Labels: 🌕 frontend, 📌 fix

#137 [FIX] 2차 QA
  assets/icon.png
  components/MyCard/CardBack.js
  pages/MyCard/EditCard.js
Labels: 🌕 frontend, 📌 fix

#138 [FIX] 2차 QA
  App.js
  components/Bluetooth/NoCardsView.js
  components/Bluetooth/ShareCardStyle.js
  components/Space/AcceptCardView.js
  pages/Space/DetailTeamSpace.js
  pages/home/HomeStyle.js
Labels: 🌕 frontend, 📌 fix
