Repository teamBeNU/SSOP_Expo, pull requests merged in 2024-10, with the labels that each got.

#60 [FEAT] 스페이스 - 팀 백엔드 연결
  App.js
  assets/AppBar/ic_search_regular_line.svg
  assets/icons/LinkShareImage.svg
  assets/icons/ic_blue_point.svg
  assets/icons/ic_close_small_line.svg
  assets/icons/ic_contact_small_line.svg
  assets/icons/ic_lists.svg
  assets/icons/ic_person_small_fill.svg
  assets/icons/ic_pink_point.svg
  assets/icons/ic_radio_check_white.svg
  assets/icons/ic_share_small_line.svg
  assets/icons/ic_swap_regular.svg
  assets/icons/ic_teamsp.svg
  assets/icons/radio_button_checked.svg
  assets/icons/radio_button_unchecked.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ListCardsView.js
  components/Bluetooth/NoCardsView.js
  components/Bluetooth/ShareCard.js
  components/Bluetooth/ShareCardStyle.js
  components/CreateCard/DropDown.js
  components/CreateTeamSpace/FanTemplate.js
  components/CreateTeamSpace/StudentTemplate.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/CreateTeamSpace/WorkerTemplate.js
  components/EnterTeamSp/HostFanFalse.js
  components/EnterTeamSp/HostFanTrue.js
  components/EnterTeamSp/HostFreeFalse.js
  components/EnterTeamSp/HostFreeTrue.js
  components/EnterTeamSp/HostStudentFalse.js
  components/EnterTeamSp/HostStudentTrue.js
  components/EnterTeamSp/HostTemplate.js
  components/EnterTeamSp/HostWorkerFalse.js
  components/EnterTeamSp/HostWorkerTrue.js
  components/Space/MySpaceDetailView.js
  components/Space/SpaceList.js
  components/Space/SpaceModal.js
  package-lock.json
  package.json
  pages/Bluetooth/Bluetooth.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/CreateTeamSp/CreateTmSpStyle.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/LinkShare/LinkShare.js
  pages/Notify/Notify.js
  pages/Space/DetailGroup.js
  pages/Space/DetailTeamSpace.js
  pages/Space/DetailTeamSpaceScreen.js
  pages/Space/EditGroupPage.js
  pages/Space/EditTeamSpace.js
  pages/Space/MySpace.js
  pages/Space/MySpaceManage.js
  pages/Space/Space.js
  pages/Space/SpaceStyle.js
  pages/Space/TeamSpace.js
  pages/home/HomeStyle.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend

#66 [FIX] 카드 생성, 마이페이지, 팀스페이스 지정 템플릿 BE 연결
  .gitignore
  App.js
  assets/icons/avatarCustom/ic_auto.svg
  assets/icons/avatarCustom/ic_redo_small_line.svg
  assets/icons/avatarCustom/ic_restart_small_line.svg
  assets/icons/avatarCustom/ic_undo_small_line.svg
  assets/icons/ic_home_gray.svg
  components/CreateCard/AvatarCustom.js
  components/CreateCard/AvatarCustomStyles.js
  components/CreateCard/BottomSheet.js
  components/CreateCard/BottomSheetStyle.js
  components/CreateCard/SelectCover.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudent.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateStyles.js
  components/CreateCard/TemplateWorker.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/EnterTeamSp/HostFanFalse.js
  components/EnterTeamSp/HostFanTrue.js
  components/EnterTeamSp/HostFreeFalse.js
  components/EnterTeamSp/HostStudentFalse.js
  components/EnterTeamSp/HostStudentTrue.js
  components/EnterTeamSp/HostTemplate.js
  components/EnterTeamSp/HostWorkerFalse.js
  components/EnterTeamSp/HostWorkerTrue.js
  components/MyPage/CancelModal.js
  components/MyPage/MyPageModal.js
  components/MyPage/MyPageModalStyle.js
  package-lock.json
  pages/CreateCard/CreateCard.js
  pages/CreateCard/CreateCardStyle.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/Login/Login.js
  pages/MyPage/MyPage.js
  pages/MyPage/MyPageStyle.js
  pages/MyPage/Service/DownArrow.js
  pages/MyPage/Service/FAQ.js
  pages/MyPage/Service/QuestionsCollection.js
  pages/MyPage/Service/ServiceAgree.js
  pages/MyPage/Service/ServiceStyles.js
  pages/MyPage/UserAccount.js
  pages/MyPage/UserInfo.js
  pages/MyPage/UserInfoStyle.js
  pages/MyPage/UserPhoneNumber.js
  pages/MyPage/UserPw.js
  pages/Space/DetailTeamSpace.js
  pages/Space/TeamSpace.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 🎨 UI, 📌 fix

#67 [FEAT] #58 팀스페이스 관리
  App.js
  assets/icons/ic_share_blue.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/ShareCard.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/EnterTeamSp/HostTemplate.js
  components/MyCard/CardBackMember.js
  components/MyCard/CardFrontMember.js
  components/MyCard/CardMember.js
  components/Space/MySpaceDetailView.js
  components/Space/SpaceList.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/CreateTeamSp/CreateTmSpStyle.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/Space/DetailTeamSpaceScreen.js
  pages/Space/EditTeamSpace.js
  pages/Space/Space.js
  pages/Space/TeamSpace.js
  utils/templateMapping.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#68 [FEAT] #62 카드 관련 페이지
  App.js
  assets/icons/ic_contact_small_line.svg
  assets/splash.png
  components/CreateTeamSpace/TeamSpTemplate.js
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardStyle.js
  components/MyCard/CardViewStyle.js
  components/MyCard/GridCardView.js
  components/MyCard/ListCardView.js
  package-lock.json
  package.json
  pages/CheckCard/CheckCard.js
  pages/CheckCard/CheckCardDetail.js
  pages/CheckCard/CheckCardStyle.js
  pages/CheckCard/Memo.js
  pages/MyCard/EditCard.js
  pages/MyCard/EditCardStyle.js
  pages/MyCard/MyCardStyle.js
  pages/Space/AcceptCard.js
  pages/home/Home.js
  utils/cardSampleData.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#72 [FEAT]#70 detail group
  assets/icons/ic_RightArrow_small_line.svg
  assets/icons/ic_folder-add.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Space/AcceptCardView.js
  components/Space/SpaceList.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/MyPage/MyPageStyle.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
  pages/Space/EditGroupPage.js
  pages/Space/MySpace.js
  pages/Space/Space.js
  pages/Space/SpaceStyle.js
Labels: ➕ feat, 🌕 frontend

#78 [FEAT] #77 카카오 토큰 연결과 카드 관련 기능
  .env
  App.js
  app.json
  assets/Card/ic_contact.svg
  assets/Card/ic_link.svg
  assets/Card/ic_mail.svg
  assets/icons/ic_editcard.svg
  assets/icons/ic_more_regular_line.svg
  assets/icons/ic_radioBtn_all.svg
  assets/icons/ic_radioBtn_notSelect.svg
  assets/icons/ic_share_small_line.svg
  components/Login/KaKaoLogin.js
  components/MyCard/AddTel.js
  components/MyCard/Card.js
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardFront.js
  components/MyCard/CardStyle.js
  components/MyCard/CardViewStyle.js
  components/MyCard/DeleteCardAPI.js
  components/MyCard/GridCardView.js
  components/MyCard/ListCardView.js
  components/MyCard/Memo.js
  components/MyCard/MemoStyle.js
  eas.json
  package-lock.json
  pages/CheckCard/CheckCardDetail.js
  pages/Login/SignUp.js
  pages/MyCard/DeleteMyCard.js
  pages/MyCard/EditCard.js
  pages/MyCard/EditCardCover.js
  pages/MyCard/EditCardStyle.js
  pages/MyCard/MyCard.js
  pages/MyCard/MyCardStyle.js
  pages/MyCard/MyCardsView.js
  pages/MyCard/MyCardsViewStyle.js
  pages/Space/AcceptCard.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend

#79 Feat/#74 avatar custom
  assets/avatars/clothes/clothes-1.png
  assets/avatars/face/eyebrows/eyebrows-1.png
  assets/avatars/face/eyes/eyes-1.png
  assets/avatars/face/face/face-1.png
  assets/avatars/hair/back/back-1.png
  assets/avatars/hair/front/front-1.png
  assets/avatars/sampleAva.png
  components/CreateCard/AvatarCustom.js
  components/CreateCard/AvatarCustomStyles.js
  components/CreateCard/SelectCover.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateStyles.js
  components/CreateCard/TemplateWorker.js
  components/CreateCard/avatarItems.js
  components/EnterTeamSp/HostTemplate.js
  components/MyPage/MyPageModalStyle.js
  package-lock.json
  pages/CreateCard/CreateCard.js
  pages/Login/Login.js
  pages/MyPage/MyPage.js
  pages/MyPage/UserInfo.js
  pages/MyPage/UserPhoneNumber.js
  pages/MyPage/UserPw.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend
