Repository teamBeNU/SSOP_Expo, pull requests merged in 2024-11, with the labels that each got.

#86 [FIX] 홈 화면 수정 / 받은 카드 날짜
  App.js
  app.json
  assets/HomeIcon/folderback.svg
  assets/HomeIcon/ic_arrow.svg
  assets/HomeIcon/ic_arrow_white.svg
  assets/HomeIcon/ic_bluetooth.svg
  assets/HomeIcon/ic_linkshare.svg
  assets/HomeIcon/ic_teamspin.svg
  assets/HomeIcon/ic_teamspnew.svg
  assets/HomeIcon/img_banner.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ShareCard.js
  components/Bluetooth/ShareCardStyle.js
  components/Space/AcceptCardView.js
  components/Space/ExchangeModal.js
  components/Space/ExchangeModalStyle.js
  eas.json
  package-lock.json
  package.json
  pages/Notify/Notify.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
  pages/Space/Space.js
  pages/home/Home.js
  pages/home/HomeStyle.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#88 [FIX] #85 팀스페이스 및 변경된 디자인 수정
  assets/icons/ic_add_small_line.svg
  assets/icons/ic_add_white.svg
  assets/icons/ic_edit.svg
  assets/icons/ic_myspace.svg
  assets/icons/ic_share_gray.svg
  assets/icons/ic_share_white.svg
  assets/icons/ic_space.svg
  assets/icons/ic_swap.svg
  assets/icons/ic_swap_regular.svg
  assets/icons/ic_teamsp.svg
  assets/icons/ic_teamspace.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ListCardsView.js
  components/Bluetooth/ListCardsViewStyle.js
  components/Bluetooth/ShareCardStyle.js
  components/EnterTeamSp/HostStudentTrue.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardViewStyle.js
  components/MyCard/ListCardView.js
  components/Space/AcceptCardView.js
  components/Space/MySpaceDetailView.js
  package-lock.json
  pages/EnterTeamSp/EnterTeamSp.js
  pages/LinkShare/LinkShare.js
  pages/MyCard/MyCard.js
  pages/MyCard/MyCardsView.js
  pages/MyCard/MyCardsViewStyle.js
  pages/Space/AcceptCard.js
  pages/Space/DetailTeamSpace.js
  pages/Space/DetailTeamSpaceScreen.js
  pages/Space/EditGroupPage.js
  pages/Space/EditTeamSpace.js
  pages/Space/Space.js
  pages/Space/SpaceStyle.js
  pages/Space/TeamSpace.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#89 [FEAT] #84 연락처 복수 저장
  components/MyCard/AddTel.js
  components/MyCard/CardBack.js
  components/MyCard/GridCardView.js
  components/MyCard/ListCardView.js
  package-lock.json
  package.json
  pages/CheckCard/CheckCardDetail.js
  pages/Space/AcceptCard.js
  pages/Space/SpaceStyle.js
Labels: ➕ feat, 🌕 frontend

#94 [FEAT] 자체블루투스 -> 디바이스 공유 탭
  %ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
  .expo/devices.json
  .gitignore
  .yarn/cache/@expo-cli-npm-0.18.30-114d31821a-b4d422bac8.zip
  .yarn/install-state.gz
  App.js
  app.json
  assets/icons/ic_RightArrow_small_line.svg
  assets/icons/ic_trash.svg
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/CardStyle.js
  components/MyCard/CardViewStyle.js
  components/MyCard/GridCardView.js
  components/MyCard/ListCardView.js
  package.json
  pages/Bluetooth/Bluetooth.js
  pages/Login/Login.js
  pages/Login/LoginStyle.js
  pages/Login/SignIn.js
  pages/Login/SignUp.js
  pages/Login/SignUpStyle.js
  pages/MyCard/DeleteMyCard.js
  pages/MyCard/EditCard.js
  pages/MyCard/MyCard.js
  pages/MyCard/MyCardStyle.js
  pages/MyCard/MyCardsView.js
  pages/MyCard/MyCardsViewStyle.js
  pages/Space/AcceptCard.js
  pages/Space/DetailTeamSpaceScreen.js
  textStyles.js
  utils/parseHTMLData.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#96 [FEAT] #87 딥링크 / 디자인 수정
  .idea/.name
  .idea/vcs.xml
  .idea/workspace.xml
  App.js
  app.json
  assets/HomeIcon/HomeImageBack.svg
  assets/HomeIcon/HomeImageCenter.svg
  assets/HomeIcon/HomeImageFront.svg
  assets/HomeIcon/graphic01.png
  assets/HomeIcon/graphic02.png
  assets/HomeIcon/graphic03.png
  assets/HomeIcon/graphic04.png
  assets/HomeIcon/homeBanner.png
  assets/HomeIcon/ic_teamspin.svg
  assets/HomeIcon/ic_teamspnew.svg
  assets/HomeIcon/logo_line.svg
  assets/icons/LinkShareImage.svg
  assets/icons/ic_myspace.svg
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ShareCard.js
  components/Bluetooth/ShareCardStyle.js
  components/MyCard/CardDetailView.js
  components/Space/AcceptCardView.js
  components/Space/SpaceModalStyle.js
  package-lock.json
  package.json
  pages/LinkShare/LinkShare.js
  pages/LinkShare/LinkShareStyle.js
  pages/MyCard/MyCard.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
  pages/Space/EditGroupPage.js
  pages/Space/MySpace.js
  pages/Space/Space.js
  pages/Space/TeamSpace.js
  pages/home/Home.js
  pages/home/HomeStyle.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#97 [FEAT] #93 아바타 커스터마이징
  App.js
  components/Avatar/AvatarCustom.js
  components/Avatar/AvatarCustomStyles.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateWorker.js
  components/EnterTeamSp/HostTemplate.js
  components/MyCard/CardDetailView.js
  package-lock.json
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/MyCard/EditCardCover.js
  utils/avatarCapture.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#100 [FEAT] #90 팀스페이스 오류 수정 및 경고창 수정
  assets/icons/ic_myspace.svg
  assets/profile/fan.svg
  assets/profile/free.svg
  assets/profile/student.svg
  assets/profile/worker.svg
  components/Avatar/AvatarCustomStyles.js
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/ListCardsViewStyle.js
  components/CreateCard/TemplateStyles.js
  components/CreateTeamSpace/StudentTemplate.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/EnterTeamSp/HostTemplate.js
  components/MyCard/CardStyle.js
  components/Space/ExchangeModalStyle.js
  components/Space/MySpaceDetailView.js
  package-lock.json
  pages/Bluetooth/BluetoothStyle.js
  pages/CheckCard/CheckCardStyle.js
  pages/CreateCard/CreateCardStyle.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/CreateTeamSp/CreateTmSpStyle.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/LinkShare/LinkShareStyle.js
  pages/MyCard/MyCardStyle.js
  pages/MyCard/MyCardsViewStyle.js
  pages/MyPage/MyPageStyle.js
  pages/SearchCard/HomeSearchCard.js
  pages/SearchCard/SearchCardStyle.js
  pages/Space/DetailTeamSpace.js
  pages/Space/DetailTeamSpaceScreen.js
  pages/Space/MySpace.js
  pages/Space/Space.js
  pages/Space/SpaceStyle.js
  pages/Space/TeamSpace.js
  pages/home/Home.js
  pages/home/HomeStyle.js
  yarn.lock
Labels: ➕ feat, 🌕 frontend, 📌 fix

#103 [FIX] #99 카드 에러 수정
  .expo/devices.json
  assets/icons/logo_insta.png
  assets/icons/logo_x.png
  components/MyCard/CardBack.js
  components/MyCard/CardDetailView.js
  components/MyCard/GridCardView.js
  components/MyCard/ListCardView.js
  pages/MyCard/DeleteMyCard.js
  pages/MyCard/MyCard.js
  pages/MyCard/MyCardsView.js
Labels: 🌕 frontend, 📌 fix

#105 Feat/#87 link share
  .env
  .expo/devices.json
  App.js
  app.json
  assets/icons/LinkShareImage.svg
  assets/icons/homeBanner
  components/Bluetooth/CardsView.js
  components/Space/AcceptCardView.js
  components/Space/SpaceList.js
  package-lock.json
  package.json
  pages/LinkShare/LinkShare.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
  pages/Space/MySpace.js
  pages/home/Home.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#106 [FIX] svg 수정
  .expo/devices.json
  App.js
  assets/createCard/coverAvatar.svg
  assets/createCard/coverPicture.svg
  assets/images/cardCover-1.png
  assets/images/cardCover-2.png
  assets/images/cardDone.png
  assets/profile/fan.svg
  assets/profile/free.svg
  assets/profile/student.svg
  assets/profile/worker.svg
  assets/teamSp/bg_gradation.svg
  components/EnterTeamSp/HostTemplate.js
  components/MyCard/Memo.js
  pages/CreateCard/CreateCard.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
  pages/LinkShare/LinkShare.js
  pages/Login/Login.js
  pages/MyCard/EditCard.js
  pages/Space/AcceptCard.js
  pages/Space/DetailGroup.js
Labels: 🌕 frontend, 📌 fix

#107 [FIX] 최종발표 전 머지
  App.js
  components/Bluetooth/CardViewsStyle.js
  components/Bluetooth/CardsView.js
  components/Bluetooth/ListCardsViewStyle.js
  components/Bluetooth/ShareCardStyle.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/MyCard/CardBack.js
  components/Space/MySpaceDetailView.js
  eas.json
  package-lock.json
  package.json
  pages/Bluetooth/Bluetooth.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/Notify/Notify.js
  pages/SearchCard/HomeSearchCard.js
  pages/SearchCard/SearchCardStyle.js
  pages/Space/DetailTeamSpace.js
  pages/Space/EditTeamSpace.js
  pages/Space/SpaceStyle.js
  pages/home/Home.js
  utils/parseHTMLData.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#108 [FIX] 카드 생성 수정
  components/CreateCard/SelectCover.js
  components/CreateCard/TemplateFree.js
  components/EnterTeamSp/DropDown.js
  components/EnterTeamSp/FreeSelectBtn.js
  components/EnterTeamSp/HostFanFalse.js
  components/EnterTeamSp/HostFanTrue.js
  components/EnterTeamSp/HostFreeFalse.js
  components/EnterTeamSp/HostStudentFalse.js
  components/EnterTeamSp/HostStudentTrue.js
  components/EnterTeamSp/HostTemplate.js
  components/EnterTeamSp/HostWorkerFalse.js
  components/EnterTeamSp/HostWorkerTrue.js
  package-lock.json
  pages/EnterTeamSp/EnterTeamSp.js
  pages/EnterTeamSp/EnterTeamSpStyle.js
Labels: 🌕 frontend, 📌 fix

#110 [FEAT] #109 QR 공유
  .expo/README.md
  .expo/devices.json
  App.js
  app.json
  assets/HomeIcon/ic_bluetooth.svg
  components/Bluetooth/BottomSheetStyle.js
  components/Bluetooth/QRBottomSheet.js
  components/MyCard/CardDetailView.js
  components/Space/AcceptCardView.js
  package-lock.json
  package.json
  pages/Bluetooth/Bluetooth.js
  pages/Bluetooth/BluetoothStyle.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/MyCard/MyCard.js
  pages/Space/DetailGroup.js
  pages/Space/Space.js
  pages/home/Home.js
Labels: ➕ feat, 🌕 frontend, 📌 fix

#112 [FIX] 카드 생성, 마이페이지 수정
  components/CreateCard/Modal/CustomModal.js
  components/CreateCard/Modal/CustomModalStyle.js
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateStyles.js
  components/CreateCard/TemplateWorker.js
  components/CreateTeamSpace/TeamSpTemplate.js
  components/EnterTeamSp/HostFanTrue.js
  components/EnterTeamSp/HostStudentTrue.js
  components/EnterTeamSp/HostTemplate.js
  components/EnterTeamSp/HostWorkerTrue.js
  components/MyPage/MyPageModal.js
  components/MyPage/MyPageModalStyle.js
  pages/CreateCard/CreateCardStyle.js
  pages/CreateTeamSp/CreateTeamSp.js
  pages/EnterTeamSp/EnterTeamSp.js
  pages/Login/Login.js
  pages/MyPage/UserAccount.js
  pages/MyPage/UserInfo.js
  pages/MyPage/UserPhoneNumber.js
  pages/MyPage/UserPw.js
Labels: 🌕 frontend, 📌 fix

#115 [FEAT] 온보딩
  App.js
  assets/images/onboarding1.png
  assets/images/onboarding2.png
  assets/images/onboarding3.png
  assets/images/onboarding4.png
  components/CreateCard/TemplateFan.js
  components/CreateCard/TemplateFree.js
  components/CreateCard/TemplateStudentSchool.js
  components/CreateCard/TemplateStudentUniv.js
  components/CreateCard/TemplateWorker.js
  pages/CreateCard/CreateCard.js
  pages/CreateCard/CreateCardStyle.js
  pages/Onboarding/Onboarding.js
  pages/Onboarding/OnboardingStyle.js
  pages/home/Home.js
Labels: ➕ feat, 🌕 frontend
